CREATE PROCEDURE SP_ACTIVE_GM_AUTH
	@ID VARCHAR(50),
	@ACTIVE BIT
AS
BEGIN
	DECLARE @CODE INT = 0;
	SELECT @CODE = CODE_NUMBER FROM TBL_USER_CODE_NUMBER WHERE ID = @CODE;

	IF @CODE = 0
		RETURN 999;

	UPDATE TBL_GM SET ACTIVE = @ACTIVE WHERE ID = @ID;

	RETURN 0;
END