USE [GameDB]
GO
/****** Object:  StoredProcedure [dbo].[SP_ACTIVE_GM_AUTH]    Script Date: 2025-05-04 ¿ÀÀü 1:04:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[SP_ACTIVE_GM_AUTH]
	@ID VARCHAR(50),
	@ACTIVE BIT
AS
BEGIN
	DECLARE @CODE INT = 0;

	SET LOCK_TIMEOUT 20000;

	SELECT @CODE = CODE_NUMBER 
	FROM TBL_USER_CODE_NUMBER WITH(NOLOCK) 
	WHERE ID = @ID;

	IF @CODE = 0
		RETURN 999;
	BEGIN TRY
		UPDATE TBL_GM SET ACTIVE = @ACTIVE WHERE ID = @CODE;
	END TRY
	BEGIN CATCH
		PRINT 'ACTIVE_GM_AUTH : ' + ERROR_MESSAGE();
		RETURN -1;
	END CATCH

	RETURN 0;
END