CREATE PROCEDURE SP_CREATE_CHARACTER
	@ID VARCHAR(50),
	@GENDER INT,
	@JOB INT
AS
BEGIN
	BEGIN TRAN
	BEGIN TRY
		INSERT INTO TBL_CHAR_GENDER_INFO VALUES(@ID,@GENDER);


		INSERT INTO TBL_CHAR_JOB_INFO VALUES(@ID,@JOB,1);
		

		INSERT INTO TBL_CHAR_LAST_MAP_INFO(ID,MAP_ID,X,Y) VALUES(@ID,0,300,300);
		

		INSERT INTO TBL_CHAR_LEVEL_INFO VALUES(@ID,1,0);
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT 'CREATE_CHARACTER : ' + ERROR_MESSAGE()
		RETURN -1;
	END CATCH
		
	COMMIT TRAN
	RETURN 0;
END