CREATE PROCEDURE SP_READ_CHARACTER
	@ID VARCHAR(50)
AS
BEGIN
    SELECT 
        G.ID,
        G.GENDER,
        J.JOB,
        J.JOB_LEVEL,
        L.MAP_ID,
        L.X,
        L.Y,
        LV.CURRENT_LEVEL,
        LV.CURRENT_EXP
    FROM TBL_CHAR_GENDER_INFO G
    INNER JOIN TBL_CHAR_JOB_INFO J ON G.ID = J.ID
    INNER JOIN TBL_CHAR_LAST_MAP_INFO L ON G.ID = L.ID
    INNER JOIN TBL_CHAR_LEVEL_INFO LV ON G.ID = LV.ID
    WHERE G.ID = @ID
END;