USE [GameDB]
GO
/****** Object:  StoredProcedure [dbo].[SP_UPDATE_GENDER]    Script Date: 2025-05-04 ¿ÀÀü 1:58:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[SP_UPDATE_GENDER]
	@ID VARCHAR(50),
	@GENDER INT
AS
BEGIN
	DECLARE @USER_CODE INT = 0;

	SET LOCK_TIMEOUT 20000;

	SELECT @USER_CODE = CODE_NUMBER 
	FROM TBL_USER_CODE_NUMBER WITH(NOLOCK) 
	WHERE ID = ID;

	IF @USER_CODE = 0
		RETURN 999;

	BEGIN TRY
		UPDATE TBL_CHARACTER_PRESET SET GENDER = @GENDER WHERE ID = @USER_CODE;
	END TRY
	BEGIN CATCH
		PRINT dbo.FN_GET_ERROR_MESSAGE('TBL_CHARACTER_PRESET');
		RETURN -1;
	END CATCH

	RETURN 0;
END
