CREATE PROCEDURE SP_UPDATE_GENDER
	@ID VARCHAR(50),
	@GENDER INT
AS
BEGIN
	DECLARE @USER_CODE INT = 0;
	SELECT @USER_CODE = CODE_NUMBER FROM TBL_USER_CODE_NUMBER WHERE ID = ID;

	IF @USER_CODE = 0
		RETURN 999;
	UPDATE TBL_CHARACTER_PRESET SET GENDER = @GENDER WHERE ID = @USER_CODE;

	RETURN 0;
END
