CREATE PROCEDURE SP_UPDATE_PRESET
	@ID VARCHAR(50),
	@PRESET_NUMBER INT
AS
BEGIN
	DECLARE @USER_CODE INT = 0;
	SELECT @USER_CODE = CODE_NUMBER FROM TBL_USER_CODE_NUMBER WHERE ID = @ID;
	
	IF @USER_CODE = 0
		RETURN 999;

	UPDATE TBL_CHARACTER_PRESET SET PRESET_NUMBER = @PRESET_NUMBER WHERE ID = @USER_CODE;

	RETURN 0;
END