USE [GameDB]
GO
/****** Object:  StoredProcedure [dbo].[SP_UPDATE_PRESET]    Script Date: 2025-05-04 ¿ÀÀü 1:35:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[SP_UPDATE_PRESET]
	@ID VARCHAR(50),
	@PRESET_NUMBER INT
AS
BEGIN
	DECLARE @USER_CODE INT = 0;
	
	SET LOCK_TIMEOUT 20000;

	SELECT @USER_CODE = CODE_NUMBER 
	FROM TBL_USER_CODE_NUMBER WITH(NOLOCK) 
	WHERE ID = @ID;
	
	IF @USER_CODE = 0
		RETURN 999;
	
	BEGIN TRY
		UPDATE TBL_CHARACTER_PRESET SET PRESET_NUMBER = @PRESET_NUMBER WHERE ID = @USER_CODE;
	END TRY
	BEGIN CATCH
		PRINT '[SP_UPDATE_PRESET] : ' + ERROR_MESSAGE();
		RETURN -1;
	END CATCH

	RETURN 0;
END