USE GameDB;
GO

IF OBJECT_ID('dbo.TBL_CHAR_LAST_MAP_INFO' , 'U') IS NOT NULL
	DROP TABLE dbo.TBL_CHAR_LAST_MAP_INFO;
GO

CREATE TABLE TBL_CHAR_LAST_MAP_INFO
(
	ID INT NOT NULL PRIMARY KEY,
	MAP_ID INT NOT NULL,
	X INT NOT NULL,
	Y INT NOT NULL
);