USE GameDB;
GO

IF OBJECT_ID('dbo.TBL_USER_CODE_NUMBER', 'U') IS NOT NULL
	DROP TABLE dbo.TBL_USER_CODE_NUMBER
GO

CREATE TABLE TBL_USER_CODE_NUMBER
(
	CODE_NUMBER INT IDENTITY PRIMARY KEY,
	ID VARCHAR(50) NOT NULL
);