USE GameDB;
GO

IF OBJECT_ID('dbo.TBL_CHARACTER_PRESET' , 'U') IS NOT NULL
	DROP TABLE dbo.TBL_CHARACTER_PRESET;
GO

CREATE TABLE TBL_CHARACTER_PRESET
(
	ID INT NOT NULL PRIMARY KEY,
	GENDER INT NOT NULL,
	PRESET_NUMBER INT NOT NULL
);