USE GameDB;
GO

IF OBJECT_ID('dbo.TBL_CHAR_JOB_INFO' , 'U') IS NOT NULL
	DROP TABLE dbo.TBL_CHAR_JOB_INFO;
GO

CREATE TABLE TBL_CHAR_JOB_INFO
(
	ID INT NOT NULL PRIMARY KEY,
	JOB INT NOT NULL,
	JOB_LEVEL INT NOT NULL
);