CREATE TABLE TBL_CHAR_LAST_MAP_INFO
(
	SEQ INT IDENTITY(0,1) PRIMARY KEY,
	ID VARCHAR(50) NOT NULL,
	MAP_ID INT NOT NULL,
	X INT NOT NULL,
	Y INT NOT NULL
);
/*LAST MAP INFO 테이블은 캐릭터 생성시에만 INSERT되고 나머지에는 UPDATE (SELECT)만 사용되기에 인덱스 사용하자*/
CREATE INDEX ACCOUNT_ID_INDEX ON TBL_CHAR_LAST_MAP_INFO(ID);