USE GameDB;
GO

IF OBJECT_ID('dbo.TBL_CHAR_LEVEL_INFO' , 'U') IS NOT NULL
	DROP TABLE dbo.TBL_CHAR_LEVEL_INFO;
GO

CREATE TABLE TBL_CHAR_LEVEL_INFO
(
	ID INT NOT NULL PRIMARY KEY,
	CURRENT_LEVEL INT NOT NULL,
	CURRENT_EXP INT NOT NULL
);