USE AccountDB;
GO

ALTER TABLE dbo.TBL_ACCOUNT
	ADD	SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
					CONSTRAINT DF_SYS_START DEFAULT SYSUTCDATETIME() NOT NULL,
				SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
					CONSTRAINT DF_SYS_END DEFAULT '9999-12-31 23:59:59.9999999' NOT NULL,
				PERIOD FOR SYSTEM_TIME(SysStartTime, SysEndTime);
GO

ALTER TABLE dbo.TBL_ACCOUNT
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TBL_ACCOUNT_HISTORY));
GO