USE [AccountDB]
GO

/****** Object:  Table [dbo].[TBL_ACCOUNT]    Script Date: 2025-05-05 ¿ÀÈÄ 5:45:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_ACCOUNT](
	[idx] [int] IDENTITY(1,1) NOT NULL,
	[ID] [varchar](50) NOT NULL,
	[PW] [varbinary](128) NOT NULL,
	[IP] [varchar](50) NOT NULL,
	[GM] [bit] NULL,
	[NICKNAME] [nvarchar](16) NULL,
	[SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
	[SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[TBL_ACCOUNT_HISTORY])
)
GO

ALTER TABLE [dbo].[TBL_ACCOUNT] ADD  DEFAULT ((0)) FOR [GM]
GO

ALTER TABLE [dbo].[TBL_ACCOUNT] ADD  CONSTRAINT [DF_TBL_ACCOUNT_NICKNAME]  DEFAULT (N'GUEST') FOR [NICKNAME]
GO

ALTER TABLE [dbo].[TBL_ACCOUNT] ADD  CONSTRAINT [DF_SYS_START]  DEFAULT (sysutcdatetime()) FOR [SysStartTime]
GO

ALTER TABLE [dbo].[TBL_ACCOUNT] ADD  CONSTRAINT [DF_SYS_END]  DEFAULT ('9999-12-31 23:59:59.9999999') FOR [SysEndTime]
GO


